export {default as AHomeStack} from './AHome/AHomeStack'
export {default as AStudentStack} from './AStudent/AStudentStack'
export {default as ACalenderStack} from './ACalender/ACalenderStack'
export {default as AAccountStack} from './AAccount/AAccountStack'
export {default as AEducationStack} from './AEducation/AEducationStack'