export {default as Home} from './home/Home'
export {default as Student} from './student/Student'
export {default as Calender} from './calender/Calender'
export {default as Account} from './account/Account'
export {default as Education} from './education/Education'