export {default as PHomeStack} from './PHome/PHomeStack'
export {default as PStudentStack} from './PStudent/PStudentStack'
export {default as PCalenderStack} from './PCalender/PCalenderStack'
export {default as PAccountStack} from './PAccount/PAccountStack'
export {default as PEducationStack} from './PEducation/PEducationStack'